name: CI tests

on:
  pull_request:

  push:
    branches:
      - main

  workflow_dispatch:
    # This is to allow running the workflow manually on github.com


jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure
        run: >
          cmake -B ./build/
          -D SIMPLE_RISCV_EMU_BUILD_TESTS=ON
          -D SIMPLE_RISCV_EMU_BUILD_APP=OFF
          -D CMAKE_BUILD_TYPE=RelWithDebInfo
          -D CMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build ./build/

      - name: Run tests
        run: ./build/tests
