name: CI tests

on:
  pull_request:

  push:
    branches:
      - main

  workflow_dispatch:
    # This is to allow running the workflow manually on github.com


jobs:
  RunTests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Install project dependencies and configure
        run: cmake -B ./build/ -D BUILD_TESTING=ON -D CMAKE_BUILD_TYPE=RelWithDebInfo
        env:
          VCPKG_ROOT: ${{ env.VCPKG_INSTALLATION_ROOT }}

      - name: Compile
        run: cmake --build ./build/
        env:
          VCPKG_ROOT: ${{ env.VCPKG_INSTALLATION_ROOT }}

      - name: Run tests
        run: ./build/tests
